### ISSUE TITLE
ldFlags?

### ISSUE THREAD

**Issue by kashw2** [studio-b12/goat#56]
Hi! 

I'm currently packaging goat for the Nix package manager (can follow along [here](https://github.com/NixOS/nixpkgs/pull/275801)) and it doesn't look like there's any current way to use linker flags to inject things like the `Version`, `Commit Hash`, `Build Date` etc at build time. At least not how I usually see them in some of the other packages I maintain that we use ldFlags for. 

These ldFlags can be useful in Nix (and nixpkgs) as they provide us a way to do what are known as 'passthru' tests which are used to test certain things such as stdout from a cli program. ldFlags here would be useful as it would allow us to pass in the version of goat we are building from and then also perform a test by running `goat --version` and having the correct version displayed. 

Any information on the addition of ldFlags (or where to find them if they already exist) would be greatly appreciated.

**Comment by zekroTJA** [comment]
Hey! Oh cool, thats sounds great!

Yeah, currently, the fields `Version`, `CommitHash` and `BuildDate` are generated by the [`version.sh`](https://github.com/studio-b12/goat/blob/main/scripts/version.sh) script, which generates a `version.go`  in `internal/version/version.go`. This script is executed by the taskfile when using the `build` and `release` targets. But it should be possible to pass these values in via the `-X` ldflags. But therefore, if I recall correctly, these variables must not be constants which would be needed to be changed.

Let me know what you think about this and if you still need the ldflags. Then we can try to make it work with setting these variables using them.

**Comment by kashw2** [comment]
Hi again and happy new year to you and the contributors of goat. 

If it is possible to expose these variables via constants in a package inside of goat that'd be great and would mean we could specify with `-X` values like the `Version` field for users. I haven't had much luck so far figuring out a way that would be as easily maintainable as using the linker for a single file / package that defines these values. So far the only way I've been able to think of that we could do it in Nix is by:

- Using `substituteInPlace` on `version.sh` and using the `--replace` flag to alter the values, would potentially work however could break if ever it is changed upstream
- Using a patch via `git diff` on `version.sh` however this would mean we'd have to regenerate the patch each version update, right now version updates would be pretty simple as we're building from source and there's an automated tool to do it all for us.
- Using a patch via `git diff` where we manually create the `version.go` file however this would run into the same issue above.

**Comment by zekroTJA** [comment]
Hey, thank you and I wish you a great new year as well!

I've updated the version variables in the `internal/version.go` from constants to variables so that they can be set via `X` LDFlags.

The result looks as following:
```
❯ go build -ldflags='-X github.com/studio-b12/goat/internal/version.Version=v1.0.1 -X github.com/studio-b12/goat/internal/version.CommitHash=some-commit-hash -X github.com/studio-b12/goat/internal/version.BuildDate=some-build-date' ./cmd/goat/main.go
❯ ./main --version
goat v1.0.1 (some-commit-hash some-build-date go1.22rc1)
```

Feel free to let us know if that fits into your workflow or if there is still something that needs to be adjusted. :)

**Comment by kashw2** [comment]
Hi, sorry for the long response time. I've just gotten around to implementing this in https://github.com/NixOS/nixpkgs/pull/275801/commits/d3a89245dd82c149bb4caf1556a28fb43312533e and it works a charm. Thanks for your efforts on this

**Comment by zekroTJA** [comment]
Hey, absolutely no problem! Thank you very much for your effort to add the tool to Nixpkgs! :)
